### ISSUE TITLE
Github Pages - Error 404 "There isn't a GitHub Pages site here."

### ISSUE THREAD

**Issue by regal-shabazz** [Onyinyexyz/TinDog#1]
Hello, great work on your project, I admire it and would like to contribute to it sometime, however, there seems to be an issue with the deployment of your website via GitHub pages. I reckon you look into it so we can see the result of your code visually.

**Comment by Onyinyexyz** [comment]
Thank you @regal-shabazz I'll look forward to it. I definitely ran into some difficulties with the GitHub Pages. I'll get it fixed, I promise.

**Comment by Onyinyexyz** [comment]
@regal-shabazz Issue has been fixed!
